- name: Only run update
  apt:
    update_cache: yes
    
- name: Install packages dependencies
  apt:
    name:
        - net-tools
        - vim
        - wget
        - python3
        - python3-pip
    state: present

- name: Install mariadb-server
  apt:
    name: 
        - mariadb-server

- name: Make sure mariadb service is running
  systemd:
    name: mariadb
    state: started
    enabled: yes  

- name: Install pip packages
  pip:
    name:
        - pymysql
    executable: pip3

- name: Configure my.cnf settings.
  lineinfile:
    dest: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    line: "bind-address = 0.0.0.0"
    state: present
  notify: restart mariadb
