- include_tasks: RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- name: "Create mysql user"
  include_tasks: Users.yml

- name: "Create database mysql"
  include_tasks: Database.yml
