- name: Mysql | Create a new pass for user
  command: openssl rand -base64 8
  register: mysql_user_pass

- name: Create `/root/.mypass` with user password credentials
  template:
    src:  user.db.j2
    dest: /root/.mypass
    owner: root
    mode: 0600
    force: yes
