- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true
    
- name: Install packages
  yum:
    name:
        - epel-release
        - net-tools
        - openssl
        - telnet
        - python3
        - python3-pip
    state: present

- name: Install pip packages
  pip:
    name:
        - pymysql
 
- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes
